import fs from "node:fs/promises";
import path from "node:path";
import { BspAssetApplicator } from "./bspAssetApplicator";
import { MTB4_ARCHITECTURE } from "./architecture";
import { CliArgs } from "./types";

export async function createApplicationFromSdk(args: CliArgs): Promise<void> {
  await fs.mkdir(args.destDir, { recursive: true });

  const applicator = new BspAssetApplicator();
  await applicator.apply({
    sdkDir: args.sdkDir,
    bsp: args.bsp,
    destinationDir: args.destDir,
    architecture: MTB4_ARCHITECTURE,
  });

  await writeReadme(args);
}

async function writeReadme(args: CliArgs): Promise<void> {
  const targetFile = path.join(args.destDir, "README.generated.md");
  const content = [
    "# Generated Application",
    "",
    `SDK: ${args.sdkDir}`,
    `BSP: ${args.bsp}`,
    `Destination: ${args.destDir}`,
    "",
    "This application was generated by createproj.",
  ].join("\n");

  await fs.writeFile(targetFile, content, "utf8");
}
